language: bash
env:
  global:
    - DEPLOY_HOST=palette-rpm.brilliant-data.net
    - DEPLOY_PATH=/var/palette-rpm-repo
    - DEPLOY_USER=palette-rpm
    # DEPLOY_PASS
    - secure: CcmCsAfHlekgxsoYTNiFemACIqOP5SOl7cxCG4RpVQtw130/CQW5DECRO8NTs5MtguM1Z9bqXt3DdHT7lfPpIPI1nb0YT6bQ2VYx98x34dMOnJYjOE+yI8rZajcR1a0ve9gT5OOzO3JOhc/ufx74sSZfprvPNkkkCLMlwhPWSQI9J+3FimDAyNY26RWAnIb+BCev+lg1p7JNAIy+8F4Dv/mOvZ4Fhx/a2SSgB3RaXcW5j1S1XIqlWdK0rlqQ7Xp2fDmizsUN+SpDYmLNdZRnXJ94tF8zfhlqDvIScj3VxsWgfFhXP6XL5TTCXDvjFdABrEGodlr3OgRX+7oL+qQZFKVOUGL21AYJPkUg9FazLVd52fjxd4UJYLZwb4kW1D/6WSiK9RJDbfb/GvvTSh6u6YAgI4+5RQRmfUzB8CruFQDzgnnEF+/ZOHPDWet193b16eStFCJWlAkFfy9u8uakfzppqVCip6dqRJ3dNYGJLTFmD93gQWfn2SWUM3GBk7jlGJHZOXqT1MBmDZp0UbqDJgiGOeS9qQW1ZyWkNURgWYlUZNVfZYiggYoht65ZFXEYBH5g5grvmkzkR3dK6iLVpxFB7olPjAgG1eV8evAsJ6nf9RPItchoFYCuhjNP1fS/TZqVlxvauf9NOUao6TY7eFuQwjWDbXvgI4kgQGMD5CM=
addons:
  apt:
    packages:
      - rpm
      - sshpass
install: true
script:
  - rpmbuild -bb --buildroot $(pwd) -D "version 3.2.3" -D "buildrelease ${TRAVIS_BUILD_NUMBER}" -D "_rpmdir rpm-build/_build" palette-supervisor.spec
deploy:
  provider: script
  script: ./deploy.sh
  skip_cleanup: true
  on:
    branch: master
notifications:
  email:
    on_success: never
    on_failure: never
